---

- name: Create Helm install directory
  ansible.builtin.file:
    path: "{{ osd_helm_dir }}"
    state: directory

- name: Pull Helm tar
  ansible.builtin.get_url:
    url: "{{ osd_helm_url }}"
    dest: "{{ osd_helm_dir }}"

- name: Grab tar file
  ansible.builtin.find:
    paths: "{{ osd_helm_dir }}"
    patterns: '*.tar.gz'
  register: osd_helm_tar

- name: Tar xzvf helm
  ansible.builtin.unarchive:
    src: "{{ item.path }}"
    dest: "{{ osd_helm_dir }}"
    remote_src: true
  with_items: "{{ osd_helm_tar.files }}"

- name: Find helm file
  ansible.builtin.find:
    paths: "{{ osd_helm_dir }}/"
    patterns: 'helm'
    recurse: true
  register: osd_helm_file

- name: Copy helm binary to bin location
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ osd_ulb_dir }}"
    remote_src: true
    mode: 0755
  with_items: "{{ osd_helm_file.files }}"
