---

- name: Add helm opensearch repo
  kubernetes.core.helm_repository:
    name: "{{ osd_helm_opensearch_version }}"
    repo_url: "{{ osd_helm_opensearch_repo }}"

- name: Deploy Opensearch through helm
  kubernetes.core.helm:
    name: "{{ osd_opensearch_name }}"
    namespace: "{{ osd_opensearch_namespace }}"
    chart_ref: opensearch/opensearch
    values_files:
      - '{{ osd_opensearch_dir }}/{{ osd_customvalues }}'

- name: Wait until Opensearch has successfully deployed
  ansible.builtin.command: '{{ osd_ulb_dir }}/kubectl wait --for=condition=Ready pod/opensearch-cluster-master-0'
  register: opensearch_result
  until: "opensearch_result is not failed"
  retries: 40
  delay: 2
  changed_when: false
