---

- name: Add helm opensearch repo
  kubernetes.core.helm_repository:
    name: "{{ osd_helm_opensearch_version }}"
    repo_url: "{{ osd_helm_opensearch_repo }}"

- name: Deploy Opensearch through helm
  kubernetes.core.helm:
    name: "{{ osd_opensearch_name }}"
    namespace: "{{ osd_opensearch_namespace }}"
    create_namespace: true
    chart_ref: opensearch/opensearch
    values_files:
      - '{{ osd_opensearch_dir }}/{{ osd_customvalues }}'

- name: Wait till the Object is created
  kubernetes.core.k8s_info:
    kind: Pod
    wait: yes
    namespace: '{{ osd_opensearch_namespace }}'
    wait_sleep: 10
    wait_timeout: 600
